### ISSUE TITLE
Things I realised from the output file

### ISSUE THREAD

**Issue by stefanscholz8** [nathangeffen/faststi#7]
- [ ] The maximum age group value should be 15. Agents that reach 16 should die immediatly

- [x] Almost all agents have become HIV positive. In function "event_age" in the last if condition "smaller (<)" needs to be exchanged with "greater" (>)

- [ ] The relative share of persons in relationships increases from 52.4 to 66.0 percent. Might be due to the age groups above 15, though.
- [x] The death date is mostly zero.

**Comment by nathangeffen** [comment]
Fixed.
